### ISSUE TITLE
Can't remove validator when redelegation already in progress

### ISSUE THREAD

**Issue by PFC-developer** [st4k3h0us3/steak-contracts#9]
more for discussion.
-
but as removing validators today equally distributes their tokens to pool, it can get held up by people undelegating/redelegating away.

I propose when we remove we limit it to say to redistribute to lowest 10/10%.. 
and potentially add a new function to 'freeze' a validator so they can't get any more delegations.
this should potentially also help with gas fees

thoughts/prayers?

**Comment by larry0x** [comment]
my opinion is that liquid staking should be a part of the L1 stack, which has the full ability to customize the staking logics to suite the LSD's need. 3rd party protocols have inherit limitations
